@host=http://localhost:3000/api/auth

POST {{host}}/login
Content-Type: application/json

{
    "username": "Yogesh",
    "password": "Yogesh@123"
}

###
POST {{host}}/register
Content-Type: application/json

{
    "firstname": "Yogesh",
    "lastname": "Sahu",
    "username": "Yogesh",
    "password": "Yogesh@123"
}
