@host=http://localhost:3000/api/products
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MmJjNWQxYWMxMDJhYTE3NDBiMTA5YzUiLCJ1c2VybmFtZSI6IllvZ2VzaCIsImlhdCI6MTY1NjUxMTc3MCwiZXhwIjoxNjU2NTIyNTcwfQ.P4QqKcddJRNvzxChvABDQsPOb1mWwIrHZjEAuM8ojmw

GET {{host}}

###
GET {{host}}/62bc5ccfc102aa1740b109c2

###
POST {{host}}/upload
Authorization: Bearer {{token}}
Cache-Control: no-cache
Postman-Token: a5e46360-ac35-1b05-e1f9-76bfd433dcfb
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="products.csv"
Content-Type: text/csv

< ../data/products.csv
------WebKitFormBoundary7MA4YWxkTrZu0gW--
