GET http://localhost:3000/user

###
POST http://localhost:3000/user
Content-Type: application/json

{
    "firstname":"Yogesh",
    "lastname" : "Sahu",
    "username":"yogesh123",
    "password":"yogesh333"
}
